name: Release NodeJS app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Builds devopsdockeruh/docker-hy.github.io
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: potatogolem/expressapptest:latest
